version: '3'

services:
  db:
    image: postgres:12.5
    environment:
      POSTGRES_DB: ecommerce_game
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
  backend:
    build: ./backend
    command: [ "sh", "entrypoint.sh" ]
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://teste:teste@db:5432/mydatabase
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
