# Generated by Django 4.1.6 on 2023-02-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(default="", max_length=255, verbose_name="image"),
        ),
        migrations.AddField(
            model_name="product",
            name="score",
            field=models.IntegerField(default=0, verbose_name="score"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name="price"),
        ),
    ]
