# Generated by Django 4.1.6 on 2023-02-12 02:56

import json

from django.db import migrations, models, transaction


def load_file(apps, schema_editor):
    Product = apps.get_model("market", "Product")

    with open("products.json", encoding="utf-8") as file:
        products = json.load(file)
        list(map(lambda x: Product.objects.create(**x), products))


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0004_alter_purchase_created_alter_purchase_customer"),
    ]

    operations = [migrations.RunPython(load_file, None)]
