# Generated by Django 4.1.6 on 2023-02-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_product_image_product_score_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name="price"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="quantity"),
        ),
    ]
