# Generated by Django 4.1.6 on 2023-02-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_cart_price_alter_cart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="customer",
            field=models.CharField(max_length=100, verbose_name="customer"),
        ),
    ]
